# Generated by Django 6.1.1 on 2026-09-22 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter the name of your form', max_length=200)),
                ('textbox_prompt', models.TextField(blank=True, help_text='Describe the question or purpose of this field', max_length=700)),
                ('checkbox_prompt', models.TextField(blank=True, help_text='Describe the question or purpose of this field', max_length=700)),
                ('outro', models.TextField(blank=True, help_text='Leave a message or reminder for your form', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, help_text='Enter your name', max_length=200)),
                ('visitor_email', models.EmailField(blank=True, help_text='Enter your email', max_length=200)),
                ('textbox', models.TextField(blank=True, help_text='Answer the prompt', max_length=700)),
                ('checkbox', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.form')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter the name of your link', max_length=200)),
                ('link_url', models.URLField(help_text='Enter the URL for your link')),
                ('link_image', models.ImageField(blank=True, help_text='Upload a link icon or image', upload_to='link_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter the name you want visitors to see', max_length=200)),
                ('email', models.EmailField(help_text='Enter the email you want visitors to see', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Enter the # you want visitors to see', max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Add a short bio', max_length=1000)),
                ('profile_image', models.ImageField(blank=True, help_text='Upload a profile image', upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text='Enter the name of your project', max_length=200)),
                ('project_description', models.TextField(blank=True, help_text='Enter a brief description of your project', max_length=500)),
                ('project_link', models.URLField(help_text='Enter the URL for your project')),
                ('project_image', models.ImageField(blank=True, help_text='Upload a project image', upload_to='project_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter the name or purpose of your resume', max_length=200)),
                ('file', models.FileField(help_text='Upload your resume file', upload_to='resumes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
