# Generated by Django 6.1.1 on 2026-09-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
    ]
