# Generated by Django 6.1.1 on 2026-10-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_rename_project_description_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='include_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='include_name',
            field=models.BooleanField(default=False),
        ),
    ]
