# Generated by Django 6.1.1 on 2026-10-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_form_include_email_form_include_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='display_name',
            new_name='form_name',
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='visitor_email',
            field=models.EmailField(blank=True, help_text='Enter your email', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='visitor_name',
            field=models.CharField(blank=True, help_text='Enter your name', max_length=200, null=True),
        ),
    ]
