# Generated by Django 6.1.1 on 2026-10-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_rename_display_name_form_form_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='name_required',
            field=models.BooleanField(default=False),
        ),
    ]
